/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;
import uni.aed.bignumbers.BigInt;

/**
 *
 * @author AndreP
 */
public class FrmBigNumbers extends javax.swing.JFrame {

    /**
     * Creates new form FrmBigNumbers
     */
    public FrmBigNumbers() {
        initComponents();
        // Centering window
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        lblIntroduceValues = new javax.swing.JLabel();
        lblNum1 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JTextField();
        lblNum2 = new javax.swing.JLabel();
        bttnSum = new javax.swing.JButton();
        bttnSub = new javax.swing.JButton();
        bttnMultiplication = new javax.swing.JButton();
        bttnDivision = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        bttnClose = new javax.swing.JButton();
        bttnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("BIG NUMBER OPERATIONS");

        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });
        txtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNum1KeyTyped(evt);
            }
        });

        lblIntroduceValues.setText("Introduzca valores:");

        lblNum1.setText("Valor 1:");

        txtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum2ActionPerformed(evt);
            }
        });

        lblNum2.setText("Valor 2:");

        bttnSum.setIcon(new javax.swing.ImageIcon("C:\\Users\\AndreP\\OneDrive - UNIVERSIDAD NACIONAL DE INGENIERIA\\Code\\Algorithms & Data Structures\\AlgorithmsAndDataStructures\\Sort&SearchApp\\src\\main\\resources\\images\\arithmeticOperations\\plus.jpg")); // NOI18N
        bttnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSumActionPerformed(evt);
            }
        });

        bttnSub.setIcon(new javax.swing.ImageIcon("C:\\Users\\AndreP\\OneDrive - UNIVERSIDAD NACIONAL DE INGENIERIA\\Code\\Algorithms & Data Structures\\AlgorithmsAndDataStructures\\Sort&SearchApp\\src\\main\\resources\\images\\arithmeticOperations\\less.jpg")); // NOI18N
        bttnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSubActionPerformed(evt);
            }
        });

        bttnMultiplication.setIcon(new javax.swing.ImageIcon("C:\\Users\\AndreP\\OneDrive - UNIVERSIDAD NACIONAL DE INGENIERIA\\Code\\Algorithms & Data Structures\\AlgorithmsAndDataStructures\\Sort&SearchApp\\src\\main\\resources\\images\\arithmeticOperations\\mult.jpg")); // NOI18N
        bttnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnMultiplicationActionPerformed(evt);
            }
        });

        bttnDivision.setIcon(new javax.swing.ImageIcon("C:\\Users\\AndreP\\OneDrive - UNIVERSIDAD NACIONAL DE INGENIERIA\\Code\\Algorithms & Data Structures\\AlgorithmsAndDataStructures\\Sort&SearchApp\\src\\main\\resources\\images\\arithmeticOperations\\div.jpg")); // NOI18N
        bttnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDivisionActionPerformed(evt);
            }
        });

        lblResult.setText("Resultado:");

        txtResult.setEditable(false);

        bttnClose.setText("Close");
        bttnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCloseActionPerformed(evt);
            }
        });

        bttnClear.setText("Clear");
        bttnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttnClear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttnClose))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtResult))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bttnMultiplication)
                                            .addComponent(bttnSum))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bttnSub)
                                            .addComponent(bttnDivision))
                                        .addGap(0, 70, Short.MAX_VALUE))
                                    .addComponent(txtNum2)
                                    .addComponent(txtNum1))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIntroduceValues, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblIntroduceValues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNum1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNum2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnSum)
                    .addComponent(bttnSub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnMultiplication)
                    .addComponent(bttnDivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnClose)
                    .addComponent(bttnClear))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        txtNum2.requestFocus();
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void txtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum2ActionPerformed
        bttnSum.requestFocus();
    }//GEN-LAST:event_txtNum2ActionPerformed

    private BigInt[] getData(){
        BigInt[] nums = new BigInt[2];
        try{
            nums[0] = new BigInt(txtNum1.getText());
            nums[1] = new BigInt(txtNum2.getText());
        }
        catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        return nums;
    }
    private void bttnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSumActionPerformed
        BigInt[] nums = getData();
        if(nums == null || nums[0] == null || nums[1] == null) return;

        BigInt resultado = nums[0].sum(nums[1]);
        txtResult.setText(resultado.toString(","));
    }//GEN-LAST:event_bttnSumActionPerformed

    private void bttnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSubActionPerformed
        BigInt[] nums = getData();
        if(nums == null || nums[0] == null || nums[1] == null) return;

        BigInt resultado = nums[0].sub(nums[1]);
        txtResult.setText(resultado.toString(","));
    }//GEN-LAST:event_bttnSubActionPerformed

    private void bttnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMultiplicationActionPerformed
        BigInt[] nums = getData();
        if(nums == null || nums[0] == null || nums[1] == null) return;

        BigInt resultado = nums[0].mult(nums[1]);
        txtResult.setText(resultado.toString(","));
    }//GEN-LAST:event_bttnMultiplicationActionPerformed

    private void bttnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDivisionActionPerformed
        BigInt[] nums = getData();
        if(nums == null || nums[0] == null || nums[1] == null) return;

        BigInt resultado = nums[0].simpleDiv(nums[1]);
        txtResult.setText(resultado.toString(","));
    }//GEN-LAST:event_bttnDivisionActionPerformed

    private void bttnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnClearActionPerformed
        txtNum1.setText("");
        txtNum2.setText("");
        txtResult.setText("");
    }//GEN-LAST:event_bttnClearActionPerformed

    private void bttnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttnCloseActionPerformed

    private void txtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNum1KeyTyped
        int key =evt.getKeyChar();
        boolean numero=key>=48 && key<=57;
        if(!numero)
            evt.consume();
    }//GEN-LAST:event_txtNum1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBigNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBigNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBigNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBigNumbers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBigNumbers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnClear;
    private javax.swing.JButton bttnClose;
    private javax.swing.JButton bttnDivision;
    private javax.swing.JButton bttnMultiplication;
    private javax.swing.JButton bttnSub;
    private javax.swing.JButton bttnSum;
    private javax.swing.JLabel lblIntroduceValues;
    private javax.swing.JLabel lblNum1;
    private javax.swing.JLabel lblNum2;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
